"""__TITLE__ — vertical Short built on the scene kit.

Generated by skills/create-short/scripts/scaffold.py. Out of the box this renders a ROUGH CUT:
each outline slide becomes a centred card with its `visual_beat`, plus notes and captions.
Replace scenes one at a time with real ones (skills/create-short/references/compose.md;
complete example: skills/create-short/examples/kernel-stack/build.py) and register them in
SCENES. Beat times come from ../cues.json (`cli.py cues`), never typed by hand.

Run from projects/<id>/composition:   ../../../.venv/bin/python build.py
"""

from __future__ import annotations

import json
import sys
from collections.abc import Callable
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent


def _kit_dir() -> Path:
    """The shared scene kit lives in the repo at skills/create-video/assets/."""
    for base in (HERE, *HERE.parents):
        kit = base / "skills" / "create-video" / "assets"
        if (kit / "scenekit.py").exists():
            return kit
    sys.exit("scenekit.py not found: this Short must live inside the yt-setup repo "
             "(projects/<id>/composition). https://github.com/mohitmishra786/yt-setup")


sys.path.insert(0, str(_kit_dir()))
from scenekit import K, Scene, outro, set_layout, title_card, write_index  # noqa: E402,F401

set_layout("portrait")
TITLE = "__TITLE__"
PAD, TITLE_S, OUTRO_S, LAST_HOLD = 0.6, 1.8, 2.5, 0.8
X, PW = 90, 900                       # content column: x 90..990

# One explanatory line per beat, keyed by outline slide index. A note that would show for
# under 1.2s is dropped automatically, so anchor them to beats ~1.5s+ apart.
# Example: NOTES[1] = [(0.0, "A tiny C program"), ("s1_free", "free(p) hands the memory back…")]
NOTES: dict[int, list[tuple[str | float, str]]] = {}


def rough_scene(n: int, cues: dict, slide: dict) -> Scene:
    """Placeholder until the real scene exists: the slide's visual_beat, centred."""
    s = Scene(n, cues)
    f = s.focus([300])
    s.box("card", X, f.y(0), PW, 300, slide.get("visual_beat") or slide["title"], kind="panel",
          size=38, weight=500, color=K["ink2"], extra="padding:32px;")
    f.run(["card"], [0.05])
    return s


# ---- real scenes ----------------------------------------------------------------------------
# def scene1(cues: dict) -> Scene:
#     s = Scene(1, cues)
#     f = s.focus([290, 190])                      # item heights, top to bottom
#     s.panel("code", X, f.y(0), PW, 290, ["// source · version", "line 1", "line 2"],
#             size=34, lh=52)
#     s.set("code-l0", 0.0, color=K["ink2"])       # comment line
#     s.panel("term", X, f.y(1), PW, 190, ["$ ./run", "output"], size=34, lh=52, visible=[0])
#     f.run(["code", "term"], [0.05, "s1_run"], keep=(0,))  # keep code bright (lines light up)
#     s.line_mark("code", 2, "live", "s1_free", -0.05)
#     s.show("term-l1", "s1_out", 0.0, 0.25)
#     return s

SCENES: dict[int, Callable[[dict], Scene]] = {
    # 1: scene1,
}


def main() -> None:
    outline = json.loads((PROJECT / "outline.json").read_text())
    cues_file = PROJECT / "cues.json"
    cues = json.loads(cues_file.read_text()) if cues_file.exists() else {}
    durs = json.loads((PROJECT / "audio" / "durations.json").read_text())["durations"]
    words = {int(sl["index"]): sl["words"]
             for sl in json.loads((PROJECT / "audio" / "words.json").read_text())["slides"]}
    slides = outline["slides"]
    seq = [(title_card(cues, TITLE, TITLE_S), TITLE_S, None, 0.0)]
    for k, slide in enumerate(slides, start=1):
        n = int(slide["index"])
        build = SCENES.get(n)
        scene = build(cues) if build else rough_scene(n, cues, slide)
        scene.add_notes(None, NOTES.get(n, [(0.0, slide["title"])]))
        scene.add_captions(words[n])
        hold = LAST_HOLD if k == len(slides) else 0.0
        seq.append((scene, durs[k - 1] + PAD + hold, n, durs[k - 1]))
    seq.append((outro(cues, OUTRO_S), OUTRO_S, None, 0.0))
    total = write_index(HERE, seq, TITLE)
    rough = [int(s["index"]) for s in slides if int(s["index"]) not in SCENES]
    print(f"built {len(seq)} scenes, total {total:.2f}s"
          + (f"  (rough-cut placeholders: slides {rough})" if rough else ""))


if __name__ == "__main__":
    main()
